language: c

env:
  - LUA='Lua 5.1' DB="sqlite3"
#  - LUA='Lua 5.1' DB="pgsql"
#  - LUA='Lua 5.2' DB="sqlite3"
#  - LUA='Lua 5.2' DB="pgsql"
#  - LUA='Lua 5.3' # busted depends on dkjson which doesn't (when I wrote this) support 5.3
#  - LUA='LuaJIT'  DB="sqlite3"
#  - LUA='LuaJIT'  DB="pgsql"

before_install:
  - bash .travis_setup.sh

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database test;' -U postgres

install:
  - sudo apt-get update -qq
  - sudo luarocks install busted 2.0.rc5-0
  - sudo luarocks install --server=http://rocks.moonscript.org/dev luapgsql PQ_DIR=/usr/local
  - sudo luarocks install lsqlite3

script: busted --run=travis
